music_directory     "C:/Users/devbox/Music"
playlist_directory  "C:/Users/devbox/Music/.mpd/playlists"
db_file             "C:/Users/devbox/Music/.mpd/database"
log_file            "C:/Users/devbox/Music/.mpd/log"
pid_file            "C:/Users/devbox/Music/.mpd/pid"
state_file          "C:/Users/devbox/Music/.mpd/state"
sticker_file        "C:/Users/devbox/Music/.mpd/sticker.sql"

bind_to_address     "127.0.0.1"
port                "6600"
auto_update         "yes"
restore_paused      "yes"

audio_output {
    type    "wasapi"
    name    "Windows Audio"
}
